name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp     
       # j1东京新宿	
    - name: Get j1.m3u8
      run: |
        touch ./j1.m3u8
        sudo cat >./j1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=DjdUEyjx8GM)
        EOL
        
        # j2恵比寿駅前
    - name: Get j2.m3u8
      run: |
        touch ./j2.m3u8
        sudo cat >./j2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LR7i5_pkJBg)
        EOL
        
       # j3東京西武新宿駅 
    - name: Get j3.m3u8
      run: |
        touch ./j3.m3u8
        sudo cat >./j3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=lA6TaaMGgDo)
        EOL     
        
        # j4東京新宿歌舞伎町
    - name: Get j4.m3u8
      run: |
        touch ./j4.m3u8
        sudo cat >./j4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=gFRtAAmiFbE)
        EOL     
        
        # j5静岡市さった峠
    - name: Get j5.m3u8
      run: |
        touch ./j5.m3u8
        sudo cat >./j5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=oHci2QFaRZs)
        EOL
        
        # j6静岡市富士山
    - name: Get j6.m3u8
      run: |
        touch ./j6.m3u8
        sudo cat >./j6.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=OrGQEkkEkx4)
        EOL     
        
        # j7富士山
    - name: Get j7.m3u8
      run: |
        touch ./j7.m3u8
        sudo cat >./j7.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=h6Z9v-qqHl8)
        EOL
        
        # j8富士山ライブカメラ 朝霧高原 より1
    - name: Get j8.m3u8
      run: |
        touch ./j8.m3u8
        sudo cat >./j8.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=lppy38jfV3Y)
        EOL      
        
        # j9富士山河口湖
    - name: Get j9.m3u8
      run: |
        touch ./j9.m3u8
        sudo cat >./j9.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Sv9hcJ3k5h4)
        EOL   
        
        # j10秋葉原
    - name: Get j10.m3u8
      run: |
        touch ./j10.m3u8
        sudo cat >./j10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=p9RxwPgYm7c)
        EOL
        
        # j11富士山中伊豆
    - name: Get j11.m3u8
      run: |
        touch ./j11.m3u8
        sudo cat >./j11.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=q5T3DxdzLs0)
        EOL	   
        
        # j12富士山精進湖
    - name: Get j12.m3u8
      run: |
        touch ./j12.m3u8
        sudo cat >./j12.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=qdVvly6pVhA)
        EOL		  
        
        # j13函館山ライブカメラ
    - name: Get j13.m3u8
      run: |
        touch ./j13.m3u8
        sudo cat >./j13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=s--MDmshT3I)
        EOL     
        
        # j14厳島神社の大鳥居	
    - name: Get j14.m3u8
      run: |
        touch ./j14.m3u8
        sudo cat >./j14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=AiPyUWPPsIQ)
        EOL      
        
        # j15西武新宿駅
    - name: Get j15.m3u8
      run: |
        touch ./j15.m3u8
        sudo cat >./j15.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=lA6TaaMGgDo)
        EOL   
        
        # j16大阪道頓堀	
    - name: Get j16.m3u8
      run: |
        touch ./j16.m3u8
        sudo cat >./j16.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=4Ek_1UULqq8)
        EOL   
        
        # j17東伊豆.熱川.片瀬海岸
    - name: Get j17.m3u8
      run: |
        touch ./j17.m3u8
        sudo cat >./j17.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=lKlUUfJM4vQ)
        EOL       
        
        # j18能登鹿島駅
    - name: Get j18.m3u8
      run: |
        touch ./j18.m3u8
        sudo cat >./j18.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=25600000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=THy9p2xJSek)
        EOL     
        
        # j19津山城 鶴山公園
    - name: Get j19.m3u8
      run: |
        touch ./j19.m3u8
        sudo cat >./j19.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=R7hyQ1FH4ZI)
        EOL   
        
        # j20富士山平夢 
    - name: Get j20.m3u8
      run: |
        touch ./j20.m3u8
        sudo cat >./j20.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=kg_3_1iAe3I)
        EOL	   
        
        # j21台場海浜公園
    - name: Get j21.m3u8
      run: |       
        touch ./j21.m3u8
        sudo cat >./j21.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=dJZBqTeC-h8)
        EOL   
        
        # j22羽田空港
    - name: Get j22.m3u8
      run: |
        touch ./j22.m3u8
        sudo cat >./j22.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=mwP5Z_j30t8)
        EOL    
        
        # j23国立天文台(星座分布)
    - name: Get j23.m3u8
      run: |
        touch ./j23.m3u8
        sudo cat >./j23.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=fPgVSTj7TZc)
        EOL		  
        
        # j24大阪国際空港
    - name: Get j24.m3u8
      run: |
        touch ./j24.m3u8
        sudo cat >./j24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=QUCq3tBoyK8)
        EOL		
        
        # j25博多駅
    - name: Get j25.m3u8
      run: |
        touch ./j25.m3u8
        sudo cat >./j25.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bHRaXxyvgU0)
        EOL	  
        
        # j26長崎空港
    - name: Get j26.m3u8
      run: |
        touch ./j26.m3u8
        sudo cat >./j26.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=CrxynLVl7Ss)
        EOL		  
        
        # j27新千歳空港
    - name: Get j27.m3u8
      run: |
        touch ./j27.m3u8
        sudo cat >./j27.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Azbdr5jbN6o)
        EOL		
        
        # j28日本各景點直播循環
    - name: Get j28.m3u8
      run: |
        touch ./j28.m3u8
        sudo cat >./j28.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=owaarXChaXQ)
        EOL	  
        
        # j29富士山・日本平ライブカメラ Mt.Fuji
    - name: Get j29.m3u8
      run: |
        touch ./j29.m3u8
        sudo cat >./j29.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=6Doy_fueZ_w)
        EOL	  
        
        # j30河口湖からの-富士山ライブカメラ
    - name: Get j30.m3u8
      run: |
        touch ./j30.m3u8
        sudo cat >./j30.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=bdUbACCWmoY)
        EOL	  
        
        # j31富山市ライブ配信
    - name: Get j31.m3u8
      run: |
        touch ./j31.m3u8
        sudo cat >./j31.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Np3S5E4hGlQ)
        EOL	  
        
        # j32静岡市さった峠-広重の富士山
    - name: Get j32.m3u8
      run: |
        touch ./j32.m3u8
        sudo cat >./j32.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=OrGQEkkEkx4)
        EOL	  
        
        # j33富士山ライブカメラ
    - name: Get j33.m3u8
      run: |
        touch ./j33.m3u8
        sudo cat >./j33.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Sv9hcJ3k5h4)
        EOL	
        
        # j34富士山頂からライブ配信中
    - name: Get j34.m3u8
      run: |
        touch ./j34.m3u8
        sudo cat >./j34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Pm6rYzR_bnk)
        EOL	  
        
        # j35富士山ライブカメラ 朝霧高原 より2
    - name: Get j35.m3u8
      run: |
        touch ./j35.m3u8
        sudo cat >./j35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=itSWJ25sYvA)
        EOL	  
        
        # j36浅草寺の境内-本堂側
    - name: Get j36.m3u8
      run: |
        touch ./j36.m3u8
        sudo cat >./j36.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=nOk4cd0kkp8)
        EOL	  
        
        # j37浅草寺の境内-雷門側
    - name: Get j37.m3u8
      run: |
        touch ./j37.m3u8
        sudo cat >./j37.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=hBiBadOukZA)
        EOL	  
        
        # j38北海道 いまの札幌-さっぽろ創世スクエア
    - name: Get j38.m3u8
      run: |
        touch ./j38.m3u8
        sudo cat >./j38.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=kfIQBC0hrII)
        EOL	  
        
        # j39大阪の夜景 あべのハルカス
    - name: Get j39.m3u8
      run: |
        touch ./j39.m3u8
        sudo cat >./j39.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=qz8F44n5DEw)
        EOL	 
        
        # j40東京駅丸の内口
    - name: Get j40.m3u8
      run: |
        touch ./j40.m3u8
        sudo cat >./j40.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=E3t6_5JArv8)
        EOL	
        
       # j41東京都江東区,木場公園
    - name: Get j41.m3u8
      run: |
        touch ./j41.m3u8
        sudo cat >./j41.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=hK5Ki_rvd98)
        EOL	   
        
       # j42東京 総武線 浅草橋駅 秋葉原
    - name: Get j42.m3u8
      run: |
        touch ./j42.m3u8
        sudo cat >./j42.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=mZnFfsFQUQY)
        EOL	
        
        # j43道頓堀ライブカメラ ２
    - name: Get j43.m3u8
      run: |
        touch ./j43.m3u8
        sudo cat >./j43.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=N42_ZMBDbMo)
        EOL	   
        
        # j44天橋立傘松公園
    - name: Get j44.m3u8
      run: |
        touch ./j44.m3u8
        sudo cat >./j44.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=cQXKsvwlAzc)
        EOL	  
        
        # j45十勝大橋ライブカメラ
    - name: Get j45.m3u8
      run: |
        touch ./j45.m3u8
        sudo cat >./j45.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=nk9uKVuLcGE)
        EOL	 
        
        # j46石川県羽咋市-千里浜
    - name: Get j46.m3u8
      run: |
        touch ./j46.m3u8
        sudo cat >./j46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=kqkDQNe9EQI)
        EOL	 
        
       # j47台場屋形船
    - name: Get j47.m3u8
      run: |
        touch ./j47.m3u8
        sudo cat >./j47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=dJZBqTeC-h8)
        EOL	  
        
        # j48お台場海浜公園
    - name: Get j48.m3u8
      run: |
        touch ./j48.m3u8
        sudo cat >./j48.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Q6bEzzdV7g8)
        EOL	 
        
        # j49羽田空港1
    - name: Get j49.m3u8
      run: |
        touch ./j49.m3u8
        sudo cat >./j49.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=ja-HuskdXCo)
        EOL	 
        
        # j50羽田空港2
    - name: Get j50.m3u8
      run: |
        touch ./j50.m3u8
        sudo cat >./j50.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=E8JKeypwCXI)
        EOL	      
        
        # j51羽田空港3
    - name: Get j51.m3u8
      run: |
        #EXTM3U
        touch ./j51.m3u8
        sudo cat >./j51.m3u8 <<EOL
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=5E3cNyknK3c)
        EOL     
        
        # j52羽田空港-滑走路の空
    - name: Get j52.m3u8
      run: |
        touch ./j52.m3u8
        sudo cat >./j52.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LE10LvORCBU)
        EOL	   
        
        # j53羽田空港D滑走路
    - name: Get j53.m3u8
      run: |
        touch ./j53.m3u8
        sudo cat >./j53.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=F0mMIRKUjA8)
        EOL  
        
        # j54羽田空港 機坪反向
    - name: Get j54.m3u8
      run: |
        touch ./j54.m3u8
        sudo cat >./j54.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=DLsYMox4rCY)
        EOL	
        
        # j55成田空港定点1
    - name: Get j55.m3u8
      run: |
        touch ./j55.m3u8
        sudo cat >./j55.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=RrYK6N45Mpg)
        EOL	    
        
        # j56成田空港定点2
    - name: Get j56.m3u8
      run: |
        touch ./j56.m3u8
        sudo cat >./j56.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=mYhkthVZUhY)
        EOL	  
        
        # j57いまの新千歳空港-北海道
    - name: Get j57.m3u8
      run: |
        touch ./j57.m3u8
        sudo cat >./j57.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Azbdr5jbN6o)
        EOL	  
        
        # j58新千歲機場候機樓
    - name: Get j58.m3u8
      run: |
        touch ./j58.m3u8
        sudo cat >./j58.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls  https://www.youtube.com/watch?v=PUgPJXp9ujc)
         EOL
         
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
